export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
export const RECEIVE_ONE_SEARCH_RESULT = 'RECEIVE_ONE_SEARCH_RESULT';
export const RECEIVE_SPECIFIC = 'RECEIVE_SPECIFIC';
export const RECEIVE_TRACK_FEATURES = 'RECEIVE_TRACK_FEATURES';
export const RECEIVE_VIDEO_ID = 'RECEIVE_VIDEO_ID';
export const CLEAR_STORE = 'CLEAR_STORE';
export const RECEIVE_ALBUMS = 'RECEIVE_ALBUMS';
export const RECEIVE_ALBUM_TRACKS = 'RECEIVE_ALBUM_TRACKS';
